# Generated by Django 5.0.4 on 2024-05-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(related_name='group', to='configApp.group'),
        ),
    ]
