# Generated by Django 4.2.11 on 2024-04-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
    ]
