# Generated by Django 5.0.4 on 2024-04-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configApp', '0002_student_is_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
