# Generated by Django 5.0.4 on 2024-05-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configApp', '0002_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to='configApp.teacher'),
        ),
    ]
