# Generated by Django 5.0.4 on 2024-05-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configApp', '0003_alter_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
