# Generated by Django 4.1.13 on 2024-07-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configApp', '0004_user_is_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.CharField(blank=True, max_length=500, null=True)),
                ('images', models.ManyToManyField(related_name='newsfotos', to='configApp.newsfotos')),
            ],
        ),
    ]
