# Generated by Django 5.0.4 on 2024-05-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configApp', '0005_about_server'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Server',
            new_name='Serves',
        ),
    ]
