# Generated by Django 4.1.13 on 2024-07-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configApp', '0005_newsfotos_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfotos',
            name='title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.ManyToManyField(related_name='images', to='configApp.newsfotos'),
        ),
    ]
