# Generated by Django 4.1.13 on 2024-08-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configApp', '0006_newsfotos_title_alter_news_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
